DROP DATABASE BDI221S;
GO

-- Cria��o do Banco de Dados
CREATE DATABASE BDI221S;
GO

-- Definir qual banco de dados vamos utilizar
USE BDI221S;
GO

-- TABELA PRODUTOS
DROP TABLE PRODUTOS;
GO

-- Cria��o da tabela produtos
CREATE TABLE PRODUTOS(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(255),
	TIPO CHAR(1),
	VALOR DECIMAL(4,2),
	CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID)
);
GO

-- TABELA FORMA DE PAGAMENTO
DROP TABLE FORMA_PAGAMENTO;
GO

-- CRIA��O DA TABELA FORMA DE PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO (
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(20),
	CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY(ID)
);
GO


-- DROP TABLE FUNCION�RIO
DROP TABLE FUNCIONARIO;
GO

-- CRIA��O DA TABELA FUNCION�RIO
CREATE TABLE FUNCIONARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SALARIO DECIMAL(6,2) NOT NULL,
	-- COD_ENDERECO
	TIPO CHAR(1) NULL,
	N_CONSELHO INT NULL,
	ESPECIALIDADE VARCHAR(20) NULL,
	COMISSAO DECIMAL(4,1),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID)
);
GO


-- DROP TABELA CLIENTE
DROP TABLE CLIENTE;
GO

-- CRIA��O DA TABELA CLIENTE
CREATE TABLE CLIENTE (
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	-- COD_ENDERECO
	-- TELEFONE
	EMAIL VARCHAR(50),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);
GO

-- DROP TABLE PRONTU�RIO
DROP TABLE PRONTUARIO;
GO

CREATE TABLE PRONTUARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(255),
	TEMPERATURA DECIMAL(3,1),
	PESO DECIMAL(3,1),
	CONSTRAINT PK_PRONTUARIO PRIMARY KEY(ID)
);
GO

-- TABELA PET
DROP TABLE PET;
GO

CREATE TABLE PET(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	ESPECIE VARCHAR(50),
	PORTE VARCHAR(50),
	DT_NASC DATE,
	ID_PRONTUARIO INT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(ID),
	CONSTRAINT FK_PET_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
	REFERENCES DBO.PRONTUARIO (ID)
);
GO

-- TABELA CLIENTE-PET
DROP TABLE CLIENTE_PET;
GO

CREATE TABLE CLIENTE_PET(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PET INT NOT NULL,
	CONSTRAINT PK_CLIENTE_PET PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
	REFERENCES DBO.PET (ID)
);
GO

-- TABELA VENDA
DROP TABLE VENDA;
GO

CREATE TABLE VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_FORMA_PAGAMENTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_VENDA PRIMARY KEY(ID),
	CONSTRAINT FK_VENDA_FORMA_PAGAMENTO FOREIGN KEY(ID_FORMA_PAGAMENTO)
	REFERENCES DBO.FORMA_PAGAMENTO (ID),
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_vENDA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES DBO.FUNCIONARIO (ID)
);
GO

-- TABELA PRODUTO_VENDA
DROP TABLE PRODUTO_VENDA;
GO

CREATE TABLE PRODUTO_VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_VENDA INT NOT NULL,
	CONSTRAINT PK_PRODUTO_VENDA PRIMARY KEY(ID, ID_PRODUTO, ID_VENDA),
	CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES DBO.PRODUTOS (ID),
	CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA)
	REFERENCES DBO.VENDA (ID)
);
GO


-- Adicionar o campo tipo
alter table dbo.produtos
add tipo char(1) null;
go

-- Selecionar todos as linhas da tabela
select * from produtos

-- Adicionar a chave prim�ria da tabela
ALTER TABLE PRODUTOS
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID);
GO
