-- Criação da base de dados
CREATE DATABASE BDI221;

-- Definir qual base de dados será utilizada
USE BDI221;
GO

-- Deletar (dropar) a tabela
DROP TABLE TESTE_TABLE;
GO

-- Criando tabelas no banco de dados
CREATE TABLE TESTE_TABLE(
	ID_TESTE INT IDENTITY(1,1),
	NOME VARCHAR(255) NOT NULL,
	CPF CHAR(11) NOT NULL
);

INSERT BDI221.DBO.TESTE_TABLE VALUES('MESSIAS', 12345678998);
INSERT BDI221.DBO.TESTE_TABLE VALUES('VERONICA', 92345678998);

SELECT * FROM DBO.TESTE_TABLE;

drop table dbo.produtos;

CREATE TABLE produtos(
	ID INT IDENTITY(1,1),
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(255),
	TIPO CHAR(1),
	VALOR DECIMAL(5,2)
);

INSERT DBO.produtos VALUES('MACARRÃO', 'MASSA PARA ALIMENTAÇÃO', 'P', 5.3)

SELECT * FROM DBO.PRODUTOS;

ALTER TABLE PRODUTOS
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID);
GO

-- Adicionando o campo tipo
ALTER TABLE PRODUTOS
ADD TIPO2 CHAR(1) NULL;

ALTER TABLE PRODUTOS
DROP COLUMN TIPO2;
GO

-- Adicionando a chave primária
ALTER TABLE PRODUTOS
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID);
GO