-- SELECIONANDO O BANCO DE DADOS
USE AULA_BDI_221;
GO

-- TABELA CLIENTE_PET

ALTER TABLE CLIENTE_PET
DROP CONSTRAINT FK_CLIENTE_PET_CLIENTE;

ALTER TABLE CLIENTE_PET
drop CONSTRAINT FK_CLIENTE_PET_PET;

ALTER TABLE CLIENTE_PET
ADD CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
	REFERENCES DBO.PET (ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA PET
ALTER TABLE PET
drop CONSTRAINT FK_PET_PRONTUARIO;

ALTER TABLE PET
ADD CONSTRAINT FK_PET_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
	REFERENCES DBO.PRONTUARIO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA VENDA

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_CLIENTE;

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_FORMA_PAGAMENTO;

ALTER TABLE VENDA
drop CONSTRAINT FK_VENDA_FUNCIONARIO;

ALTER TABLE VENDA
ADD CONSTRAINT FK_VENDA_FORMA_PAGAMENTO FOREIGN KEY(ID_FORMA_PAGAMENTO)
	REFERENCES DBO.FORMA_PAGAMENTO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_vENDA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES DBO.FUNCIONARIO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;


-- TABELA PRODUTO_VENDA

ALTER TABLE PRODUTO_VENDA
drop CONSTRAINT FK_PRODUTO_VENDA_VENDA;

ALTER TABLE PRODUTO_VENDA
drop CONSTRAINT FK_PRODUTO_VENDA_PRODUTO;

ALTER TABLE PRODUTO_VENDA
ADD CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES DBO.PRODUTO (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA)
	REFERENCES DBO.VENDA (ID)
	ON DELETE CASCADE ON UPDATE NO ACTION;