SELECT COUNT(TIPO) FROM DBO.FUNCIONARIO
GROUP BY TIPO
HAVING COUNT(TIPO) > 7

SELECT NOME, SALARIO FROM DBO.FUNCIONARIO
WHERE SALARIO BETWEEN 1300 AND 5000

SELECT NOME, SALARIO, TIPO FROM DBO.FUNCIONARIO
WHERE TIPO = 'A'

GROUP BY TIPO
HAVING COUNT(TIPO) > 1