USE AULA_BDI_221;

-- SELECT SIMPLES PARA VERIFICAR O CONTEÚDO
-- DE CADA TABELA

SELECT * FROM PRODUTO;

SELECT * FROM FUNCIONARIO;

SELECT * FROM VENDA;

SELECT * FROM CLIENTE;

SELECT * FROM PET;

-- MOSTRANDO APENAS LINHAS ÚNICAS

SELECT DISTINCT ESPECIE FROM PET;

SELECT DISTINCT TIPO FROM PRODUTO;

SELECT DISTINCT TIPO FROM FUNCIONARIO;

-- FILTRANDO COM WHERE

SELECT * FROM PRODUTO
WHERE TIPO = 'S'

SELECT * FROM FUNCIONARIO
WHERE TIPO = 'A'

SELECT * FROM PET
WHERE ESPECIE = 'Cachorro'

SELECT DISTINCT PORTE FROM PET
WHERE ESPECIE = 'Cachorro'

-- AGRUPANDO OS RESULTADOS

SELECT ESPECIALIDADE FROM FUNCIONARIO
GROUP BY ESPECIALIDADE, TIPO
HAVING TIPO = 'V'

SELECT TIPO, NOME FROM PRODUTO
GROUP BY TIPO, NOME, VALOR
HAVING VALOR < 30.0

-- ORDER BY

SELECT * FROM PRODUTO
ORDER BY NOME

SELECT * FROM FUNCIONARIO
ORDER BY NOME

SELECT * FROM CLIENTE
ORDER BY NOME

-- Between

SELECT * FROM PRODUTO
WHERE ID BETWEEN 3 AND 10

SELECT * FROM PRODUTO
WHERE VALOR BETWEEN 25.00 AND 60.00

-- COUNT

SELECT TIPO FROM DBO.FUNCIONARIO
GROUP BY TIPO
HAVING COUNT(TIPO) > 1