USE AULA_BDI_221;
GO


-- Funcionario de cada venda
SELECT V.ID AS ID_VENDA, A.NOME AS NOME_FUNCIONARIO FROM VENDA AS V
INNER JOIN FUNCIONARIO AS A
ON V.ID_FUNCIONARIO = A.ID

-- Funcionario e cliente de cada venda
SELECT
	V.ID AS ID_VENDA,
	A.NOME AS NOME_FUNCIONARIO,
	C.NOME AS NOME_CLIENTE
FROM VENDA AS V
INNER JOIN FUNCIONARIO AS A
	ON V.ID_FUNCIONARIO = A.ID
INNER JOIN CLIENTE AS C
	ON V.ID_CLIENTE = C.ID

-- Quanto cada funcionário total de vendas
SELECT
	F.NOME,
	SUM(P.VALOR) AS VALOR_VENDA
FROM PRODUTO AS P
INNER JOIN PRODUTO_VENDA AS PV
	ON P.ID = PV.ID_PRODUTO
INNER JOIN VENDA AS V
	ON PV.ID_VENDA = V.ID
INNER JOIN FUNCIONARIO AS F
	ON V.ID_FUNCIONARIO = F.ID
GROUP BY F.NOME
ORDER BY VALOR_VENDA DESC

-- Número de vendas de cada funcionário
SELECT
	F.NOME,
	COUNT(P.VALOR) AS VALOR_VENDA
FROM PRODUTO AS P
INNER JOIN PRODUTO_VENDA AS PV
	ON P.ID = PV.ID_PRODUTO
INNER JOIN VENDA AS V
	ON PV.ID_VENDA = V.ID
INNER JOIN FUNCIONARIO AS F
	ON V.ID_FUNCIONARIO = F.ID
GROUP BY F.NOME
ORDER BY VALOR_VENDA DESC