USE AULA_BDI_221;
GO

-- INSERT FORMAS DE PAGAMENTO

SELECT * FROM DBO.FORMA_PAGAMENTO;

INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Dinheiro');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cartão de Débito');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cartão de Crédito (Vencimento)');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Cartão de Crédito (Parcelado)');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Carnê');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Pix');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('PicPay');
INSERT INTO DBO.FORMA_PAGAMENTO VALUES ('Google Pay');

-- Teste

INSERT INTO DBO.PRODUTO VALUES ('Ração Atacama', 'Ração para cachorro de todos os portes', 'P', '199.90')
INSERT INTO DBO.PRODUTO VALUES ('Ração Whikas', 'Ração para gato de todos os portes', 'P', '99.90')

SELECT * FROM DBO.PRODUTO

-- CLIENTE
INSERT INTO DBO.CLIENTE VALUES ('CLIENTE DE TESTE 01', 'C01@EMAIL.COM')

INSERT INTO DBO.FUNCIONARIO VALUES ('FUNCIONÁRIO DE TESTE 01', '00000000000', 2564.87, 'V', 12345, 'PETS', NULL)

SELECT * FROM FUNCIONARIO

INSERT INTO VENDA VALUES (6, 1, 1) SELECT * FROM VENDA

INSERT INTO PRODUTO_VENDA VALUES (1,1)
INSERT INTO PRODUTO_VENDA VALUES (2,1)

SELECT * FROM PRODUTO_VENDA AS PV
INNER JOIN PRODUTO AS P
ON P.ID = PV.ID_PRODUTO
INNER JOIN VENDA AS V
ON V.ID = PV.ID_VENDA